services:
  - type: web
    name: djassaku-api
    env: node
    buildCommand: npm install && npm run build && mkdir -p uploads
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.yuqlhblfelywujfxbymv:Jesserjesser12345*@aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
      - key: JWT_SECRET
        value: djassaku-super-secret-jwt-key-2024
      - key: SUPABASE_URL
        value: https://yuqlhblfelywujfxbymv.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cWxoYmxmZWx5d3VqZnhieW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4NDcxMjMsImV4cCI6MjA4MjQyMzEyM30.6Z9yvGieUHrLkoqstUM06WWUF4xao2AEQpUB-yCnPZk
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://djassaku.vercel.app
